// Copyright 2026 Aananth C N
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "HailoTranscriber.h"
#include "log.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <complex>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <nlohmann/json.hpp>
#include <hailo/hailort.hpp>

using namespace hailort;

// ---------------------------------------------------------------------------
// Whisper mel-spectrogram constants
//
// MUST match the openai-whisper Python constants used when the ONNX model
// (and hence the HEF) was compiled.  Python Whisper uses N_FFT=400 (not
// a power-of-2).  Using a different N_FFT changes the frequency resolution
// of the filterbank and causes the encoder to receive out-of-distribution
// input → wrong encoder output → decoder hallucinates English phrases.
// ---------------------------------------------------------------------------
static constexpr int SAMPLE_RATE = 16000;
static constexpr int N_FFT       = 400;    // Matches Python whisper / whisper.cpp
static constexpr int HOP_LENGTH  = 160;    // 10 ms
static constexpr int WIN_LENGTH  = 400;    // = N_FFT (periodic Hann window)
static constexpr int N_MELS      = 80;
// N_FRAMES is determined at runtime from the encoder HEF input size.
// These compile-time values are only used as a fallback / for static assertions.
static constexpr int N_SAMPLES_30S = SAMPLE_RATE * 30;
static constexpr int N_FRAMES_30S  = N_SAMPLES_30S / HOP_LENGTH; // 3000

// ---------------------------------------------------------------------------
// Whisper multilingual special token IDs
//
// These values depend on the tokenizer version installed in openai-whisper.
// The authoritative source is the vocab.json generated by extract_whisper_weights.py:
//   load 50258 entries (0–50257)  →  tok.eot = 50257
//   json key "50257" = "<|endoftext|>"  →  TOK_EOT = 50257
//
// Token layout for 99-language multilingual model:
//   50257 = <|endoftext|>        (EOT — end of transcript)
//   50258 = <|startoftranscript|>(SOT)
//   50259 = <|en|>               (first language)
//   ...  99 language codes ...
//   50357 = <last language>
//   50358 = <|translate|>
//   50359 = <|transcribe|>
//   50360–50362 = mode tokens
//   50363 = <|notimestamps|>
//   50364–51864 = timestamp tokens
// ---------------------------------------------------------------------------
static constexpr int TOK_EOT           = 50257; // <|endoftext|>  (tok.eot)
static constexpr int TOK_SOT           = 50258; // <|startoftranscript|>
static constexpr int TOK_EN            = 50259; // <|en|>
static constexpr int TOK_TRANSCRIBE    = 50359; // <|transcribe|>
static constexpr int TOK_NO_TIMESTAMPS = 50363; // <|notimestamps|>
static constexpr int VOCAB_SIZE        = 51865; // multilingual vocab (matches emb shape [51865,384])
static constexpr int MAX_DECODE_TOKENS = 448;   // Whisper's hard limit

// ---------------------------------------------------------------------------
// Mixed-radix FFT — handles N = 2^k × 25 (covers N_FFT=400 = 16 × 25).
//
// Why mixed-radix:
//   N_FFT=400 = 16 × 25 = 2^4 × 5^2.  It is NOT a power of 2, so the classic
//   iterative Cooley-Tukey (bit-reversal + butterfly) only works up to N=512
//   and gives WRONG results for N=400.
//
//   Strategy: recurse with radix-2 splits (halving N) until N=25, then use a
//   precomputed O(25²) DFT.  Recursion depth is log2(16) = 4 levels.
//   Memory: O(N) temporary storage per level, trivially small.
// ---------------------------------------------------------------------------

// Precomputed twiddle table for DFT-25: W[k][j] = exp(-2πi·k·j/25)
struct Dft25Table {
    std::array<std::complex<float>, 25 * 25> W;
    Dft25Table() {
        for (int k = 0; k < 25; ++k)
            for (int j = 0; j < 25; ++j) {
                float ang = -2.0f * static_cast<float>(M_PI) * k * j / 25.0f;
                W[k * 25 + j] = {std::cos(ang), std::sin(ang)};
            }
    }
};
static const Dft25Table g_dft25;

// Recursive mixed-radix FFT.
// For even N: Cooley-Tukey radix-2.
// For N=25 (the only odd base case in the N=400 recursion): precomputed DFT.
// Generic O(N²) fallback for any other odd N (should never be reached).
static void fft_inplace(std::vector<std::complex<float>>& x) {
    int n = static_cast<int>(x.size());
    if (n <= 1) return;

    if (n % 2 == 0) {
        // Cooley-Tukey radix-2: split into even/odd sub-problems
        int h = n / 2;
        std::vector<std::complex<float>> even(h), odd(h);
        for (int i = 0; i < h; ++i) {
            even[i] = x[2 * i];
            odd[i]  = x[2 * i + 1];
        }
        fft_inplace(even);
        fft_inplace(odd);

        float step = -2.0f * static_cast<float>(M_PI) / n;
        for (int k = 0; k < h; ++k) {
            float ang = step * k;
            std::complex<float> tw(std::cos(ang), std::sin(ang));
            x[k]     = even[k] + tw * odd[k];
            x[k + h] = even[k] - tw * odd[k];
        }
    } else if (n == 25) {
        // Direct DFT for N=25 using precomputed twiddle table
        std::array<std::complex<float>, 25> tmp;
        std::copy(x.begin(), x.end(), tmp.begin());
        for (int k = 0; k < 25; ++k) {
            x[k] = {0.0f, 0.0f};
            for (int j = 0; j < 25; ++j)
                x[k] += tmp[j] * g_dft25.W[k * 25 + j];
        }
    } else {
        // Generic O(N²) DFT fallback — should never be reached for N_FFT=400
        std::vector<std::complex<float>> X(n, {0.0f, 0.0f});
        for (int k = 0; k < n; ++k)
            for (int j = 0; j < n; ++j) {
                float ang = -2.0f * static_cast<float>(M_PI) * k * j / n;
                X[k] += x[j] * std::complex<float>(std::cos(ang), std::sin(ang));
            }
        x = X;
    }
}

// ---------------------------------------------------------------------------
// Minimal numpy .npy loader — float32 only, C-order (fortran_order=False)
// ---------------------------------------------------------------------------
struct NpyArray {
    std::vector<int>   shape;
    std::vector<float> data;
    int numel() const {
        int n = 1;
        for (int s : shape) n *= s;
        return n;
    }
};

static NpyArray load_npy(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) throw std::runtime_error("Cannot open npy: " + path);

    char magic[7] = {};
    f.read(magic, 6);
    if (std::memcmp(magic, "\x93NUMPY", 6) != 0)
        throw std::runtime_error("Not a numpy file: " + path);

    uint8_t major = 0, minor = 0;
    f.read(reinterpret_cast<char*>(&major), 1);
    f.read(reinterpret_cast<char*>(&minor), 1);

    uint32_t hlen = 0;
    if (major == 1) {
        uint16_t h16 = 0;
        f.read(reinterpret_cast<char*>(&h16), 2);
        hlen = h16;
    } else {
        f.read(reinterpret_cast<char*>(&hlen), 4);
    }

    std::string hdr(hlen, '\0');
    f.read(&hdr[0], hlen);

    // Extract shape tuple from header string
    NpyArray nd;
    auto sp = hdr.find("'shape'");
    if (sp == std::string::npos) sp = hdr.find("\"shape\"");
    if (sp != std::string::npos) {
        auto p0 = hdr.find('(', sp);
        auto p1 = hdr.find(')', p0);
        std::string shape_str = hdr.substr(p0 + 1, p1 - p0 - 1);
        std::istringstream ss(shape_str);
        std::string tok;
        while (std::getline(ss, tok, ',')) {
            auto s = tok.find_first_not_of(" \t");
            if (s != std::string::npos && std::isdigit(tok[s]))
                nd.shape.push_back(std::stoi(tok.substr(s)));
        }
    }

    int n = nd.numel();
    nd.data.resize(n);
    f.read(reinterpret_cast<char*>(nd.data.data()), (std::streamsize)(n * sizeof(float)));
    return nd;
}

// ---------------------------------------------------------------------------
// Mel filterbank — precomputed once, shape [N_MELS × (N_FFT/2+1)]
//
// Preferred: load from mel_filters_80.npy (extracted from openai-whisper's
//   mel_filters.npz using scripts/extract_whisper_weights.py or:
//     python3 -c "import whisper,numpy as np,os; \
//       np.save('mel_filters_80.npy', np.load( \
//         os.path.join(os.path.dirname(whisper.__file__),'assets','mel_filters.npz'))['mel_80'])"
//
// This file must be placed alongside vocab.json in the weights directory.
// Using whisper's exact filterbank is critical: the encoder HEF was compiled
// from whisper's ONNX which uses librosa.filters.mel(sr=16000, n_fft=400, n_mels=80)
// with librosa's default O'Shaughnessy mel scale (NOT HTK) and Slaney
// normalization.  Any mismatch (wrong scale, wrong normalisation) shifts all
// mel filter centre frequencies and gains, producing garbage encoder output.
//
// Fallback (if file not found): O'Shaughnessy mel scale + Slaney normalization
// computed analytically.  Less accurate than the reference file but closer
// than HTK+Slaney which was previously used.
// ---------------------------------------------------------------------------

// O'Shaughnessy mel scale — matches librosa default (htk=False):
//   linear below 1000 Hz: mel = f / f_sp  (f_sp = 200/3 Hz per mel)
//   log above 1000 Hz:    mel = 15 + log(f/1000) / logstep  (logstep = log(6.4)/27)
// This is the mel scale used to generate whisper's mel_filters.npz.
static float hz_to_mel_oshaughnessy(float hz) {
    constexpr float F_SP       = 200.0f / 3.0f;
    constexpr float MIN_LOG_HZ = 1000.0f;
    constexpr float MIN_LOG_MEL = MIN_LOG_HZ / F_SP;   // = 15
    static const float LOGSTEP = std::log(6.4f) / 27.0f;
    if (hz < MIN_LOG_HZ)
        return hz / F_SP;
    return MIN_LOG_MEL + std::log(hz / MIN_LOG_HZ) / LOGSTEP;
}
static float mel_to_hz_oshaughnessy(float mel) {
    constexpr float F_SP       = 200.0f / 3.0f;
    constexpr float MIN_LOG_HZ = 1000.0f;
    constexpr float MIN_LOG_MEL = MIN_LOG_HZ / F_SP;
    static const float LOGSTEP = std::log(6.4f) / 27.0f;
    if (mel < MIN_LOG_MEL)
        return mel * F_SP;
    return MIN_LOG_HZ * std::exp(LOGSTEP * (mel - MIN_LOG_MEL));
}

static std::vector<float> build_mel_filterbank_fallback() {
    constexpr float f_min  = 0.0f;
    constexpr float f_max  = 8000.0f;
    constexpr int   n_bins = N_FFT / 2 + 1; // 201

    // N_MELS+2 linearly-spaced mel points → Hz  (O'Shaughnessy scale)
    std::vector<float> hz_pts(N_MELS + 2);
    float mel_min = hz_to_mel_oshaughnessy(f_min);
    float mel_max = hz_to_mel_oshaughnessy(f_max);
    for (int i = 0; i < N_MELS + 2; ++i)
        hz_pts[i] = mel_to_hz_oshaughnessy(
            mel_min + i * (mel_max - mel_min) / (N_MELS + 1));

    // FFT bin index for each mel centre
    std::vector<int> bins(N_MELS + 2);
    for (int i = 0; i < N_MELS + 2; ++i)
        bins[i] = static_cast<int>(std::floor((N_FFT + 1) * hz_pts[i] / SAMPLE_RATE));

    // Unit-peak triangular filters
    std::vector<float> fb(N_MELS * n_bins, 0.0f);
    for (int m = 0; m < N_MELS; ++m) {
        for (int k = bins[m]; k < bins[m + 1]; ++k)
            fb[m * n_bins + k] = float(k - bins[m]) / (bins[m + 1] - bins[m]);
        for (int k = bins[m + 1]; k < bins[m + 2]; ++k)
            fb[m * n_bins + k] = float(bins[m + 2] - k) / (bins[m + 2] - bins[m + 1]);
    }

    // Slaney normalization: scale by 2 / bandwidth_hz
    for (int m = 0; m < N_MELS; ++m) {
        float bw = hz_pts[m + 2] - hz_pts[m];
        if (bw > 0.0f) {
            float s = 2.0f / bw;
            for (int k = 0; k < n_bins; ++k) fb[m * n_bins + k] *= s;
        }
    }
    return fb;
}

// ---------------------------------------------------------------------------
// BPE vocabulary loader
//
// Expects a JSON file produced by:
//   python3 -c "
//     import whisper, json
//     tok = whisper.tokenizer.get_tokenizer(True)
//     json.dump({int(v): tok.decode([v]) for v in range(tok.eot+1)},
//               open('models/stt/vocab.json','w'), ensure_ascii=False)"
//
// NOTE: use ensure_ascii=False so non-ASCII characters are stored as UTF-8
// rather than \uXXXX escape sequences — the latter require a full JSON parser
// to decode correctly.
//
// Returned vector: index = token_id, value = UTF-8 string.
// ---------------------------------------------------------------------------
static std::vector<std::string> load_vocab(const std::string& path) {
    if (path.empty()) return {};

    std::ifstream f(path);
    if (!f.is_open()) {
        std::cerr << log_ts() << "[Hailo] vocab.json not found at " << path
                  << " — falling back to raw byte tokens.\n";
        return {};
    }

    // Use nlohmann::json so that \uXXXX escape sequences, embedded quotes, and
    // multi-byte UTF-8 strings are all handled correctly.
    nlohmann::json j;
    try {
        f >> j;
    } catch (const nlohmann::json::exception& e) {
        std::cerr << log_ts() << "[Hailo] vocab.json parse error: " << e.what()
                  << " — falling back to raw byte tokens.\n";
        return {};
    }

    std::vector<std::string> vocab(VOCAB_SIZE);
    int loaded = 0;
    for (auto& [key, val] : j.items()) {
        try {
            int id = std::stoi(key);
            if (id >= 0 && id < VOCAB_SIZE && val.is_string()) {
                vocab[id] = val.get<std::string>();
                ++loaded;
            }
        } catch (...) {}
    }
    std::cout << log_ts() << "[Hailo] Loaded " << loaded << " vocab entries from "
              << path << "\n";
    return vocab;
}

// ---------------------------------------------------------------------------
// Hailo model handle (one per HEF)
// ---------------------------------------------------------------------------
struct HailoModel {
    std::shared_ptr<InferModel>  infer_model;
    ConfiguredInferModel         configured;
    std::vector<std::string>     in_names;   // actual names from HEF
    std::vector<std::string>     out_names;  // actual names from HEF

    // Use the outputs()/inputs() iterators rather than output(name)/input(name)
    // because the named lookup can fail silently after configure() in some
    // HailoRT versions, returning 0 and causing run() to see an unset buffer.
    size_t input_size(const std::string& name) const {
        for (const auto& s : infer_model->inputs())
            if (s.name() == name) return s.get_frame_size();
        return 0;
    }
    size_t output_size(const std::string& name) const {
        for (const auto& s : infer_model->outputs())
            if (s.name() == name) return s.get_frame_size();
        return 0;
    }
};

// ---------------------------------------------------------------------------
// Impl
// ---------------------------------------------------------------------------
struct HailoTranscriber::Impl {
    std::unique_ptr<VDevice> vdevice;
    HailoModel               encoder;
    HailoModel               decoder;

    std::vector<float>       mel_fb;      // filterbank [N_MELS × 201]  (N_FFT/2+1 = 201)
    std::vector<float>       hann;        // Hann window [WIN_LENGTH]
    std::vector<std::string> vocab;       // id → UTF-8 string
    int                      n_enc_frames = N_FRAMES_30S; // set from HEF after load

    // matmul-split weights (loaded from .npy files)
    std::vector<float> emb_weight;    // [vocab_size × d_model]
    std::vector<float> pos_emb;       // [max_ctx × d_model]
    int                d_model     = 0;
    int                dec_seq_len = 0; // fixed decoder input length from HEF

    // CPU: embed token_ids + add positional encoding → [dec_seq_len × d_model]
    std::vector<float> embed_tokens(const std::vector<int>& token_ids) const {
        std::vector<float> out(dec_seq_len * d_model, 0.0f);
        int n = std::min((int)token_ids.size(), dec_seq_len);
        for (int i = 0; i < n; ++i) {
            int tok = token_ids[i];
            if (tok < 0 || tok >= VOCAB_SIZE) continue;
            const float* e = &emb_weight[(size_t)tok * d_model];
            const float* p = &pos_emb[(size_t)i   * d_model];
            float*       o = &out[(size_t)i * d_model];
            for (int k = 0; k < d_model; ++k) o[k] = e[k] + p[k];
        }
        return out;
    }

    // CPU: project hidden state at `pos` to logits → [VOCAB_SIZE]
    // hidden: [dec_seq_len × d_model]
    std::vector<float> project(const std::vector<float>& hidden, int pos) const {
        std::vector<float> logits(VOCAB_SIZE, 0.0f);
        const float* h = &hidden[(size_t)pos * d_model];
        for (int v = 0; v < VOCAB_SIZE; ++v) {
            float s = 0.0f;
            const float* w = &emb_weight[(size_t)v * d_model];
            for (int k = 0; k < d_model; ++k) s += h[k] * w[k];
            logits[v] = s;
        }
        return logits;
    }

    // ---------------------------------------------------------------------------
    // Log-mel spectrogram: pcm → [N_MELS × N_FRAMES] column-major float32.
    //
    // Matches openai-whisper / torch.stft with center=True (the default):
    //   torch.stft(audio, N_FFT, HOP_LENGTH, window=hann_window, center=True)
    //
    // center=True pads the signal with N_FFT//2 zeros on BOTH sides before
    // the STFT, so frame 0 is centred at sample 0 of the original signal.
    // This shifts all mel frames by N_FFT//2 = 200 samples (12.5 ms) compared
    // to a non-centred STFT.  The Hailo encoder HEF was compiled from the
    // openai-whisper ONNX which uses center=True, so we must match it.
    // ---------------------------------------------------------------------------
    std::vector<float> log_mel(const std::vector<float>& pcm) const {
        // Pad / truncate to the duration the encoder HEF was compiled for.
        int n_frames  = n_enc_frames;
        int n_samples = n_frames * HOP_LENGTH;

        // center=True: pad with N_FFT//2 REFLECT samples on each side.
        // PyTorch stft with center=True uses reflect-mode padding (pad_mode='reflect').
        // This means: audio[-k] = audio[k] (reflect at the start boundary).
        // Without reflect padding, the first few mel frames see different energy
        // than what the model was trained on.
        constexpr int PAD = N_FFT / 2;  // 200 samples
        std::vector<float> audio(n_samples + 2 * PAD, 0.0f);
        // Fill main signal
        int n_copy = std::min((int)pcm.size(), n_samples);
        std::copy_n(pcm.begin(), n_copy, audio.begin() + PAD);
        // Reflect-pad at the start: audio[PAD-k] = pcm[k-1] for k=1..PAD
        for (int k = 1; k <= PAD && k <= n_copy; ++k)
            audio[PAD - k] = pcm[k - 1];
        // Reflect-pad at the end: audio[PAD+n_samples+k] = pcm[n_copy-1-k] for k=0..PAD-1
        for (int k = 0; k < PAD && (n_copy - 1 - k) >= 0; ++k)
            audio[PAD + n_samples + k] = pcm[n_copy - 1 - k];

        constexpr int n_bins = N_FFT / 2 + 1; // 201 (N_FFT=400)
        std::vector<float> mel_out(N_MELS * n_frames, 0.0f);

        std::vector<std::complex<float>> fft_buf(N_FFT);

        for (int j = 0; j < n_frames; ++j) {
            int offset = j * HOP_LENGTH;  // into padded audio (starts at audio[PAD + j*HOP])

            for (int k = 0; k < N_FFT; ++k) {
                float w = (k < WIN_LENGTH) ? hann[k] : 0.0f;
                int   s = offset + k;
                fft_buf[k] = (s < (int)audio.size())
                             ? std::complex<float>(w * audio[s], 0.0f)
                             : std::complex<float>(0.0f, 0.0f);
            }

            fft_inplace(fft_buf);

            float power[n_bins];
            for (int k = 0; k < n_bins; ++k) {
                float re = fft_buf[k].real(), im = fft_buf[k].imag();
                power[k] = re * re + im * im;
            }

            // mel_out[m * n_frames + j] — column-major over time
            for (int m = 0; m < N_MELS; ++m) {
                float val = 0.0f;
                const float* row = &mel_fb[m * n_bins];
                for (int k = 0; k < n_bins; ++k) val += row[k] * power[k];
                mel_out[m * n_frames + j] = val;
            }
        }

        // Log compression + normalisation matching Whisper's preprocessing
        float max_val = -1e38f;
        for (float& v : mel_out) {
            v = std::log10(std::max(v, 1e-10f));
            if (v > max_val) max_val = v;
        }
        float floor = max_val - 8.0f;
        for (float& v : mel_out) v = (std::max(v, floor) + 4.0f) / 4.0f;

        return mel_out;
    }

    // ---------------------------------------------------------------------------
    // Run encoder HEF: mel → encoder hidden states.
    //
    // The HEF was compiled from the ONNX export of openai-whisper which
    // expects mel in [N_FRAMES × N_MELS] (frames-major) order, confirmed by:
    //   hailortcli parse-hef encoder.hef
    //     → Input FCR(1 × 1000 × 80)  (batch=1, frames=1000, mel_bands=80)
    //
    // Our log_mel() produces [N_MELS × N_FRAMES] (mel-major, matching numpy's
    // output from whisper.log_mel_spectrogram which returns shape [80, 1000]).
    //
    // We transpose here before sending to the NPU:
    //   mel[m × N_FRAMES + j]  →  mel_T[j × N_MELS + m]
    // ---------------------------------------------------------------------------
    std::vector<float> run_encoder(const std::vector<float>& mel) {
        if (encoder.in_names.empty() || encoder.out_names.empty())
            throw std::runtime_error("[Hailo] encoder HEF has no input/output streams");
        const std::string& in_name  = encoder.in_names[0];
        const std::string& out_name = encoder.out_names[0];

        // Transpose mel: [N_MELS × N_FRAMES] → [N_FRAMES × N_MELS]
        int n_frames = static_cast<int>(mel.size()) / N_MELS;
        std::vector<float> mel_T(mel.size());
        for (int j = 0; j < n_frames; ++j)
            for (int m = 0; m < N_MELS; ++m)
                mel_T[j * N_MELS + m] = mel[m * n_frames + j];

        auto bindings_exp = encoder.configured.create_bindings();
        if (!bindings_exp)
            throw std::runtime_error("[Hailo] encoder create_bindings failed");
        auto& bindings = bindings_exp.value();

        auto in_exp = bindings.input(in_name);
        if (!in_exp)
            throw std::runtime_error("[Hailo] encoder input '" + in_name + "' not found");
        hailo_status st = in_exp->set_buffer(
            MemoryView(mel_T.data(), mel_T.size() * sizeof(float)));
        if (st != HAILO_SUCCESS)
            throw std::runtime_error("[Hailo] encoder set_buffer (input) failed: " +
                                     std::to_string(st));

        size_t out_bytes = encoder.output_size(out_name);
        std::vector<float> enc_out(out_bytes / sizeof(float));
        auto out_exp = bindings.output(out_name);
        if (!out_exp)
            throw std::runtime_error("[Hailo] encoder output '" + out_name + "' not found");
        st = out_exp->set_buffer(MemoryView(enc_out.data(), out_bytes));
        if (st != HAILO_SUCCESS)
            throw std::runtime_error("[Hailo] encoder set_buffer (output) failed: " +
                                     std::to_string(st));

        st = encoder.configured.run(bindings, std::chrono::milliseconds(10000));
        if (st != HAILO_SUCCESS)
            throw std::runtime_error("[Hailo] encoder inference failed: " + std::to_string(st));

        return enc_out;
    }

    // ---------------------------------------------------------------------------
    // One autoregressive decoder step:
    //   encoder_out — flat float buffer from run_encoder()
    //   token_ids   — current token sequence (including SOT prefix)
    // Returns logit vector over VOCAB_SIZE.
    //
    // TODO (when decoder.hef is available):
    //   1. Verify DECODER_INPUT_ENC and DECODER_INPUT_TOKS stream names via
    //      `hailortcli parse-hef decoder.hef`
    //   2. Determine the decoder's fixed MAX_LEN (e.g. 448) and pad token_ids.
    //   3. Confirm that the HEF outputs logits for ALL positions or just the
    //      LAST position — adjust the argmax slice below accordingly.
    //   4. If the HEF uses int32 token input, cast token_ids to int32_t here.
    // ---------------------------------------------------------------------------
    // decoder_step: one autoregressive step.
    //
    // For the matmul-split architecture:
    //   CPU  → embed_tokens(token_ids)   [dec_seq_len × d_model]
    //   NPU  → decoder HEF               [dec_seq_len × d_model] hidden states
    //   CPU  → project(hidden, last_pos) [VOCAB_SIZE] logits
    //
    // If the npy weights are not loaded (d_model == 0), falls back to passing
    // raw token IDs as float32 and treating HEF output directly as logits.
    std::vector<float> decoder_step(const std::vector<float>& encoder_out,
                                    const std::vector<int>&   token_ids) {
        if (decoder.in_names.empty() || decoder.out_names.empty())
            throw std::runtime_error("[Hailo] decoder HEF has no streams");

        auto bindings_exp = decoder.configured.create_bindings();
        if (!bindings_exp)
            throw std::runtime_error("[Hailo] decoder create_bindings failed");
        auto& bindings = bindings_exp.value();

        // ---- Token input ----
        // matmul-split: CPU embeds tokens; HEF takes [dec_seq_len × d_model].
        // Fallback: raw token IDs as float32 (for non-split HEFs).
        std::vector<float> tok_buf;
        const std::string* tok_in_name = nullptr;
        const std::string* enc_in_name = nullptr;

        if (d_model > 0 && dec_seq_len > 0 && decoder.in_names.size() >= 2) {
            // matmul-split: find smaller input = embedded token sequence
            size_t sz0 = decoder.input_size(decoder.in_names[0]);
            size_t sz1 = decoder.input_size(decoder.in_names[1]);
            tok_in_name = (sz0 <= sz1) ? &decoder.in_names[0] : &decoder.in_names[1];
            enc_in_name = (sz0 <= sz1) ? &decoder.in_names[1] : &decoder.in_names[0];
            tok_buf = embed_tokens(token_ids);
        } else if (decoder.in_names.size() >= 2) {
            // No npy loaded — pass raw IDs as float32 into the smaller slot
            size_t sz0 = decoder.input_size(decoder.in_names[0]);
            size_t sz1 = decoder.input_size(decoder.in_names[1]);
            tok_in_name = (sz0 <= sz1) ? &decoder.in_names[0] : &decoder.in_names[1];
            enc_in_name = (sz0 <= sz1) ? &decoder.in_names[1] : &decoder.in_names[0];
            size_t tok_bytes = decoder.input_size(*tok_in_name);
            size_t tok_count = tok_bytes / sizeof(float);
            tok_buf.assign(tok_count, 0.0f);
            for (size_t i = 0; i < std::min(token_ids.size(), tok_count); ++i)
                tok_buf[i] = static_cast<float>(token_ids[i]);
        } else {
            // Single-input decoder — treat it as the token input
            tok_in_name = &decoder.in_names[0];
            size_t tok_bytes = decoder.input_size(*tok_in_name);
            size_t tok_count = tok_bytes / sizeof(float);
            tok_buf.assign(tok_count, 0.0f);
            for (size_t i = 0; i < std::min(token_ids.size(), tok_count); ++i)
                tok_buf[i] = static_cast<float>(token_ids[i]);
        }

        // Set token input buffer
        {
            size_t tok_bytes = tok_buf.size() * sizeof(float);
            auto in = bindings.input(*tok_in_name);
            if (!in)
                throw std::runtime_error("[Hailo] decoder token input '" +
                                         *tok_in_name + "' not found");
            hailo_status s = in->set_buffer(MemoryView(tok_buf.data(), tok_bytes));
            if (s != HAILO_SUCCESS)
                throw std::runtime_error("[Hailo] decoder tok set_buffer failed: " +
                                         std::to_string(s));
        }

        // Set encoder hidden states input (if present)
        if (enc_in_name) {
            auto in = bindings.input(*enc_in_name);
            if (!in)
                throw std::runtime_error("[Hailo] decoder enc input '" +
                                         *enc_in_name + "' not found");
            hailo_status s = in->set_buffer(
                MemoryView(const_cast<float*>(encoder_out.data()),
                           encoder_out.size() * sizeof(float)));
            if (s != HAILO_SUCCESS)
                throw std::runtime_error("[Hailo] decoder enc set_buffer failed: " +
                                         std::to_string(s));
        }

        // Set ALL output buffers (run() requires every output to have a buffer)
        std::vector<std::vector<float>> out_bufs;
        out_bufs.reserve(decoder.out_names.size());
        int    largest_idx   = 0;
        size_t largest_bytes = 0;

        for (int oi = 0; oi < (int)decoder.out_names.size(); ++oi) {
            const std::string& oname = decoder.out_names[oi];
            size_t bytes = decoder.output_size(oname);
            if (bytes == 0)
                throw std::runtime_error("[Hailo] decoder output '" + oname +
                                         "' has frame size 0");
            out_bufs.emplace_back(bytes / sizeof(float));
            auto out = bindings.output(oname);
            if (!out)
                throw std::runtime_error("[Hailo] decoder output '" + oname +
                                         "' not in bindings");
            hailo_status s = out->set_buffer(
                MemoryView(out_bufs.back().data(), bytes));
            if (s != HAILO_SUCCESS)
                throw std::runtime_error("[Hailo] decoder out set_buffer '" + oname +
                                         "' failed: " + std::to_string(s));
            if (bytes > largest_bytes) { largest_bytes = bytes; largest_idx = oi; }
        }

        hailo_status st = decoder.configured.run(bindings, std::chrono::milliseconds(5000));
        if (st != HAILO_SUCCESS)
            throw std::runtime_error("[Hailo] decoder inference failed: " + std::to_string(st));

        // ---- Detect output format from actual buffer sizes ----
        //
        // Two HEF output formats are possible regardless of whether .npy weights
        // are loaded (d_model > 0 only tells us the INPUT side is CPU-split):
        //
        //  FORMAT_LOGITS  — HEF output = [pos_per_chunk × VOCAB_SIZE] logits.
        //                   The output projection is baked into the HEF.
        //                   Use the logits directly; no CPU projection needed.
        //                   Example: tiny-whisper-decoder-fixed-sequence with
        //                   conv33/34/35/36 outputs of 1659648 bytes each
        //                   → 414912 floats ÷ 8 pos/chunk = 51864 = VOCAB_SIZE ✓
        //
        //  FORMAT_HIDDEN  — HEF output = [pos_per_chunk × d_model] hidden states.
        //                   The output projection is NOT in the HEF (true matmul-
        //                   split on both input and output).
        //                   CPU must compute: logits[v] = dot(hidden, emb_weight[v])
        //
        int last       = std::min((int)token_ids.size() - 1, dec_seq_len - 1);
        int num_chunks = (int)out_bufs.size();
        int pos_per_chunk = (num_chunks > 0 && dec_seq_len > 0)
                          ? std::max(1, dec_seq_len / num_chunks) : dec_seq_len;

        // Classify by inspecting the first output buffer's float count.
        // Two formats are possible:
        //
        //  FORMAT_LOGITS (vocab-split): each chunk covers ALL dec_seq_len positions
        //   for a contiguous slice of the vocabulary.  chunk_k has
        //   dec_seq_len × vpc_k floats where vpc_k ≈ VOCAB_SIZE / num_chunks.
        //   Because VOCAB_SIZE may not divide evenly, the first (num_chunks-1)
        //   chunks each get floor(VOCAB_SIZE/num_chunks) vocab entries and the
        //   last chunk gets the remainder.  Thus out_bufs[0].size() equals
        //   dec_seq_len × floor(VOCAB_SIZE/num_chunks), which can be
        //   pos_per_chunk floats LESS than pos_per_chunk × VOCAB_SIZE.
        //   Tolerance: allow up to pos_per_chunk floats below the naive estimate.
        //
        //  FORMAT_HIDDEN: each chunk covers pos_per_chunk positions × d_model.
        //
        enum { FORMAT_LOGITS, FORMAT_HIDDEN, FORMAT_UNKNOWN } out_fmt = FORMAT_UNKNOWN;
        if (!out_bufs.empty() && pos_per_chunk > 0) {
            size_t floats        = out_bufs[0].size();
            size_t expect_logits = (size_t)pos_per_chunk * VOCAB_SIZE;
            size_t expect_hidden = (size_t)pos_per_chunk * std::max(d_model, 1);
            // Logit rows are much larger than hidden rows (51865 vs ≤1024),
            // so test logits first to avoid a false hidden match.
            // Lower bound: allow pos_per_chunk fewer floats (uneven vocab split).
            // Upper bound: allow 64 floats extra (alignment padding).
            if (floats + (size_t)pos_per_chunk >= expect_logits &&
                floats <= expect_logits + 64)
                out_fmt = FORMAT_LOGITS;
            else if (d_model > 0 &&
                     floats >= expect_hidden && floats <= expect_hidden + 64)
                out_fmt = FORMAT_HIDDEN;
        }

        // ---- PATH A: HEF outputs hidden states; project on CPU ----
        if (out_fmt == FORMAT_HIDDEN && d_model > 0) {
            const float* h_ptr = nullptr;

            if (num_chunks > 1) {
                int chunk_idx = std::min(last / pos_per_chunk, num_chunks - 1);
                int local_pos = last % pos_per_chunk;
                const auto& chunk = out_bufs[chunk_idx];
                int start = local_pos * d_model;
                if (start + d_model <= (int)chunk.size())
                    h_ptr = chunk.data() + start;
            } else if (!out_bufs.empty()) {
                const auto& h = out_bufs[0];
                int start = last * d_model;
                if (start + d_model <= (int)h.size())
                    h_ptr = h.data() + start;
            }

            if (!h_ptr) {
                std::cerr << log_ts()
                    << "[Hailo] decoder (hidden path): cannot locate hidden[" << last
                    << "]  dec_seq_len=" << dec_seq_len << " d_model=" << d_model
                    << " chunks=" << num_chunks << "\n";
                return {};
            }

            // Output projection: logits[v] = dot(h, emb_weight[v])
            std::vector<float> logits(VOCAB_SIZE, 0.0f);
            for (int v = 0; v < VOCAB_SIZE; ++v) {
                float s = 0.0f;
                const float* w = &emb_weight[(size_t)v * d_model];
                for (int k = 0; k < d_model; ++k) s += h_ptr[k] * w[k];
                logits[v] = s;
            }
            return logits;
        }

        // ---- PATH B: HEF outputs logits directly ----
        //
        // The Hailo DFC splits the output projection along the VOCAB (channel)
        // dimension, not the sequence (width) dimension.  Each output tensor
        // covers ALL dec_seq_len positions for a contiguous range of vocab IDs.
        //
        //  NHWC layout per chunk k:  [1 × 1 × dec_seq_len × vpc_k]
        //    vpc_k  = out_bufs[k].size() / dec_seq_len   (vocab entries per chunk)
        //    chunk_k[p × vpc_k + v]  = logit for position p, vocab-range-k entry v
        //
        //  Example (this HEF):
        //    4 chunks × 32 positions × ~12966 vocab/chunk ≈ VOCAB_SIZE = 51864
        //    chunk 0 (conv33): vocab   0–12965 for all 32 positions
        //    chunk 1 (conv34): vocab 12966–25931
        //    chunk 2 (conv35): vocab 25932–38897
        //    chunk 3 (conv36): vocab 38898–51864
        //
        //  To get the full logit vector for position `last`:
        //    gather chunk_k[last × vpc_k : (last+1) × vpc_k] from every chunk k
        //    and concatenate → [VOCAB_SIZE] logits.
        if (num_chunks > 1 && dec_seq_len > 0) {
            std::vector<float> logits;
            logits.reserve(VOCAB_SIZE + 64);
            for (int ci = 0; ci < num_chunks; ++ci) {
                if (out_bufs[ci].empty()) continue;
                // vpc = vocab entries per position in this chunk.
                // Integer division: last chunk may be 1 larger to cover all vocab.
                int vpc   = static_cast<int>(out_bufs[ci].size()) / dec_seq_len;
                if (vpc <= 0) continue;
                int start = last * vpc;
                int end   = start + vpc;
                // Clip to buffer bounds (alignment padding on last chunk)
                if (end > static_cast<int>(out_bufs[ci].size()))
                    end = static_cast<int>(out_bufs[ci].size());
                if (start < end)
                    logits.insert(logits.end(),
                                  out_bufs[ci].begin() + start,
                                  out_bufs[ci].begin() + end);
            }
            return logits;
        }

        // Single output tensor
        auto& h = out_bufs[largest_idx];
        if ((int)h.size() == VOCAB_SIZE) return h;
        if ((int)h.size() > VOCAB_SIZE) {
            int start = last * VOCAB_SIZE;
            int end   = std::min(start + VOCAB_SIZE, (int)h.size());
            if (start < end)
                return std::vector<float>(h.begin() + start, h.begin() + end);
        }
        return h;
    }

    // ---------------------------------------------------------------------------
    // Greedy decode loop — returns token IDs excluding the SOT prefix
    // ---------------------------------------------------------------------------
    std::vector<int> greedy_decode(const std::vector<float>& enc_out) {
        // Whisper prompt: [SOT, lang_en, transcribe, no_timestamps]
        std::vector<int> tokens = {TOK_SOT, TOK_EN, TOK_TRANSCRIBE, TOK_NO_TIMESTAMPS};

        // For wake-word detection at most ~5 BPE tokens are needed.
        // Hard-capping at 20 prevents spending seconds on ambiguous or noisy
        // audio — Whisper's 448-token limit is never appropriate here.
        constexpr int WW_MAX_TOKENS = 20;

        // Abort if the same non-consecutive token repeats this many times.
        // (Consecutive identical tokens are prevented separately below.)
        constexpr int MAX_REPEAT = 3;
        int repeat_count = 0;
        int last_tok     = -1;

        std::vector<int> result;
        for (int step = 0; step < WW_MAX_TOKENS; ++step) {
            auto logits = decoder_step(enc_out, tokens);
            if (logits.empty()) break;

            // At step 0, log the raw (pre-suppression) top-5 tokens so we can
            // verify that the logit extraction is working correctly and see what
            // the model's unconstrained preference is.
            if (step == 0) {
                // Find top-5 indices by partial sort
                std::vector<int> idx(logits.size());
                std::iota(idx.begin(), idx.end(), 0);
                std::partial_sort(idx.begin(), idx.begin() + std::min(5, (int)idx.size()),
                                  idx.end(),
                                  [&](int a, int b){ return logits[a] > logits[b]; });
                std::cout << log_ts() << "[Hailo] Step-0 top-5 tokens (raw):";
                for (int i = 0; i < std::min(5, (int)idx.size()); ++i) {
                    int id = idx[i];
                    std::string txt = "(?)";
                    if (id >= 0 && id < (int)vocab.size() && !vocab[id].empty())
                        txt = "\"" + vocab[id] + "\"";
                    else if (id > TOK_NO_TIMESTAMPS)
                        txt = "<ts>";
                    else if (id == TOK_EOT)
                        txt = "<EOT>";
                    std::cout << "  [" << id << "]" << txt
                              << "=" << std::fixed << std::setprecision(2) << logits[id];
                }
                std::cout << "\n";
            }

            // Suppress all special/control tokens (>= TOK_SOT = 50258).
            // Only regular text tokens (0–50256) and EOT (50257) can be selected.
            //
            // Without this, the decoder sometimes picks <|translate|> (50358),
            // <|transcribe|> (50359), language tokens (50259–50357), or
            // no-timestamps (50363) and loops on them.  These tokens are valid
            // in the SOT prefix we construct, but must never appear in the
            // generated output.
            if ((int)logits.size() > TOK_EOT + 1) {
                std::fill(logits.begin() + (TOK_EOT + 1), logits.end(), -1e9f);
            }

            // Step-0 saturation guard.
            // When a loud audio transient drives NPU activations out of the
            // uint8 quantisation range, many token logits clip to the
            // dequantisation ceiling (~67).  Byte-range tokens (IDs 0–255)
            // dominate with equal, very high logits — a clear sign the encoder
            // output is garbage.  Return an empty transcript immediately rather
            // than burning WW_MAX_TOKENS decoder steps on nonsense.
            if (step == 0) {
                auto it_max = std::max_element(logits.begin(), logits.end());
                int   top1  = static_cast<int>(it_max - logits.begin());
                float max_l = (it_max != logits.end()) ? *it_max : 0.0f;
                if (max_l > 50.0f && top1 < 256) {
                    std::cout << log_ts()
                        << "[Hailo] Saturated encoder output (max_logit="
                        << std::fixed << std::setprecision(1) << max_l
                        << ", top1_id=" << top1 << ") — treating as no-speech.\n";
                    break;
                }
            }

            // Prevent consecutive identical tokens.
            // Without this the decoder can loop on a single word (e.g.
            // " we  we  we") for ambiguous audio.  Suppressing the just-
            // generated token forces a different selection at the next step.
            if (!result.empty()) {
                int prev = result.back();
                if (prev >= 0 && prev < (int)logits.size())
                    logits[prev] = -1e9f;
            }

            int next = static_cast<int>(
                std::max_element(logits.begin(), logits.end()) - logits.begin());

            if (next == TOK_EOT) break;

            // Repetition guard
            if (next == last_tok) {
                if (++repeat_count >= MAX_REPEAT) {
                    std::cerr << log_ts()
                        << "[Hailo] Repetition loop (token " << next
                        << " × " << (repeat_count + 1) << ") — aborting decode.\n";
                    result.clear(); // output is meaningless
                    break;
                }
            } else {
                repeat_count = 0;
                last_tok     = next;
            }

            tokens.push_back(next);
            result.push_back(next);

            // ---- N-gram cycle detector (k = 2..8) ----
            // If the last k tokens are identical to the k tokens before them,
            // the decoder is stuck in a hallucination loop.  Keep only the
            // first occurrence and stop.
            //
            // Catches patterns that no-consecutive-repeat cannot prevent:
            //   k=2: "(C)E)E)E)"   → detected after 6 tokens
            //   k=6: "- We're not there. - We're not there."  → after 12 tokens
            {
                bool cycle_done = false;
                int  rn         = (int)result.size();
                for (int k = 2; k <= 8 && !cycle_done; ++k) {
                    if (rn < 2 * k) continue;
                    bool same = true;
                    for (int i = 0; i < k && same; ++i)
                        same = (result[rn - 1 - i] == result[rn - 1 - k - i]);
                    if (same) {
                        std::cerr << log_ts() << "[Hailo] " << k
                                  << "-gram cycle — removing repeat and stopping.\n";
                        result.resize(rn - k); // keep first occurrence, drop dup
                        cycle_done = true;
                    }
                }
                if (cycle_done) break;
            }
        }

        // Log raw token IDs and their vocab strings so we can see exactly what
        // the decoder is producing and whether vocab lookup is working correctly.
        std::cout << log_ts() << "[Hailo] token IDs:";
        for (int id : result) std::cout << " " << id;
        std::cout << "\n";
        std::cout << log_ts() << "[Hailo] token decode:";
        for (int id : result) {
            std::string tok_text = "(?)";
            if (id >= 0 && id < VOCAB_SIZE && !vocab.empty() && !vocab[id].empty())
                tok_text = "\"" + vocab[id] + "\"";
            else if (id > TOK_NO_TIMESTAMPS)
                tok_text = "<timestamp>";
            else if (id == TOK_EOT)
                tok_text = "<EOT>";
            std::cout << " [" << id << "]=" << tok_text;
        }
        std::cout << "\n";

        return result;
    }

    // ---------------------------------------------------------------------------
    // Detokenise token IDs → UTF-8 string.
    // Uses vocab table when available; falls back to raw byte decoding.
    // ---------------------------------------------------------------------------
    std::string detokenise(const std::vector<int>& token_ids) const {
        std::string out;
        for (int id : token_ids) {
            if (id < 0 || id >= VOCAB_SIZE) continue;
            if (!vocab.empty() && !vocab[id].empty()) {
                // Replace the tiktoken Ġ (U+0120) space marker with an ASCII space
                std::string tok = vocab[id];
                size_t p = 0;
                while ((p = tok.find("\xC4\xA0", p)) != std::string::npos) {
                    tok.replace(p, 2, " ");
                    p += 1;
                }
                out += tok;
            } else {
                // Fallback: raw byte token (Whisper tokens 0-255 are byte-level)
                if (id < 256) out += static_cast<char>(id);
            }
        }
        return out;
    }
};

// ---------------------------------------------------------------------------
// HailoModel helper — loads a HEF and configures it for float32 I/O
// ---------------------------------------------------------------------------
static HailoModel load_model(VDevice& vdevice, const std::string& hef_path) {
    auto model_exp = vdevice.create_infer_model(hef_path);
    if (!model_exp)
        throw std::runtime_error("[Hailo] Failed to load HEF: " + hef_path +
                                 " (status=" + std::to_string(model_exp.status()) + ")");
    auto model = model_exp.release();

    // Request float32 I/O so we skip manual dequantisation.
    // Hailo SDK will handle the float32 ↔ uint8 conversion transparently.
    for (const auto& name : model->get_input_names()) {
        auto s = model->input(name);
        if (s) s->set_format_type(HAILO_FORMAT_TYPE_FLOAT32);
    }
    for (const auto& name : model->get_output_names()) {
        auto s = model->output(name);
        if (s) s->set_format_type(HAILO_FORMAT_TYPE_FLOAT32);
    }

    auto cfg_exp = model->configure();
    if (!cfg_exp)
        throw std::runtime_error("[Hailo] Failed to configure HEF: " + hef_path +
                                 " (status=" + std::to_string(cfg_exp.status()) + ")");

    HailoModel hm;
    hm.infer_model = std::move(model);
    hm.configured  = std::move(cfg_exp.value());
    hm.in_names    = hm.infer_model->get_input_names();
    hm.out_names   = hm.infer_model->get_output_names();
    return hm;
}

// ---------------------------------------------------------------------------
// HailoTranscriber
// ---------------------------------------------------------------------------
HailoTranscriber::HailoTranscriber(const std::string& encoder_hef_path,
                                   const std::string& decoder_hef_path,
                                   const std::string& vocab_json_path)
    : impl_(std::make_unique<Impl>())
{
    // ---- Mel filterbank ----
    // Try to load whisper's exact filterbank from mel_filters_80.npy (preferred).
    // Fall back to analytical O'Shaughnessy+Slaney computation if not found.
    if (!vocab_json_path.empty()) {
        auto sep = vocab_json_path.find_last_of("/\\");
        std::string wdir = (sep != std::string::npos)
                           ? vocab_json_path.substr(0, sep + 1) : "./";
        std::string mel_path = wdir + "mel_filters_80.npy";
        std::ifstream probe(mel_path);
        if (probe.is_open()) {
            probe.close();
            try {
                auto nd = load_npy(mel_path);
                if (nd.shape.size() == 2 &&
                    nd.shape[0] == N_MELS && nd.shape[1] == N_FFT / 2 + 1) {
                    impl_->mel_fb = std::move(nd.data);
                    std::cout << log_ts() << "[Hailo] Loaded mel_filters_80.npy "
                              << "(whisper reference filterbank) ✓\n";
                } else {
                    std::cerr << log_ts() << "[Hailo] mel_filters_80.npy has wrong shape ["
                              << nd.shape[0] << "," << (nd.shape.size()>1?nd.shape[1]:0)
                              << "] expected [" << N_MELS << "," << N_FFT/2+1
                              << "] — falling back to computed filterbank.\n";
                    impl_->mel_fb = build_mel_filterbank_fallback();
                }
            } catch (const std::exception& e) {
                std::cerr << log_ts() << "[Hailo] mel_filters_80.npy load error: "
                          << e.what() << " — falling back.\n";
                impl_->mel_fb = build_mel_filterbank_fallback();
            }
        } else {
            std::cerr << log_ts() << "[Hailo] mel_filters_80.npy not found in " << wdir
                      << " — using computed fallback filterbank (O'Shaughnessy + Slaney).\n"
                      << "  For best accuracy, extract with:\n"
                      << "    python3 -c \"import whisper,numpy as np,os; "
                      << "np.save('mel_filters_80.npy', np.load("
                      << "os.path.join(os.path.dirname(whisper.__file__),"
                      << "'assets','mel_filters.npz'))['mel_80'])\"\n";
            impl_->mel_fb = build_mel_filterbank_fallback();
        }
    } else {
        impl_->mel_fb = build_mel_filterbank_fallback();
    }

    impl_->hann.resize(WIN_LENGTH);
    for (int i = 0; i < WIN_LENGTH; ++i)
        impl_->hann[i] = 0.5f * (1.0f - std::cos(2.0f * static_cast<float>(M_PI) * i / WIN_LENGTH));

    // Load vocab table
    impl_->vocab = load_vocab(vocab_json_path);

    // Create VDevice — auto-detects the Hailo-8L
    auto vdev_exp = VDevice::create();
    if (!vdev_exp)
        throw std::runtime_error("[Hailo] VDevice::create() failed: " +
                                 std::to_string(vdev_exp.status()));
    impl_->vdevice = vdev_exp.release();

    // Load encoder and decoder HEFs
    std::cout << log_ts() << "[Hailo] Loading encoder: " << encoder_hef_path << "\n";
    impl_->encoder = load_model(*impl_->vdevice, encoder_hef_path);

    // Derive the required mel frame count from the encoder input tensor size.
    // Expected input: [N_MELS × n_frames] float32 — n_frames varies by HEF duration.
    if (!impl_->encoder.in_names.empty()) {
        size_t in_bytes = impl_->encoder.input_size(impl_->encoder.in_names[0]);
        impl_->n_enc_frames = static_cast<int>(in_bytes / sizeof(float) / N_MELS);
        int duration_s = impl_->n_enc_frames * HOP_LENGTH / SAMPLE_RATE;
        std::cout << log_ts() << "[Hailo] Encoder audio window: "
                  << impl_->n_enc_frames << " mel frames (" << duration_s << "s)\n";
    }

    std::cout << log_ts() << "[Hailo] Loading decoder: " << decoder_hef_path << "\n";
    impl_->decoder = load_model(*impl_->vdevice, decoder_hef_path);

    // ---------------------------------------------------------------------------
    // matmul-split weights: look for token_embedding_weight_*.npy and
    // onnx_add_input_*.npy in the same directory as vocab_json_path.
    // These are used for CPU embedding lookup + positional add (decoder input)
    // and CPU output projection (hidden states → logits).
    // ---------------------------------------------------------------------------
    if (!vocab_json_path.empty()) {
        auto sep = vocab_json_path.find_last_of("/\\");
        std::string wdir = (sep != std::string::npos)
                           ? vocab_json_path.substr(0, sep + 1) : "./";

        // Discover npy files by the known naming pattern
        auto try_load = [&](const std::string& suffix, std::vector<float>& dst,
                            std::vector<int>& shape_out) {
            std::ifstream probe(wdir + suffix);
            if (!probe.is_open()) return false;
            probe.close();
            try {
                auto nd = load_npy(wdir + suffix);
                dst       = std::move(nd.data);
                shape_out = nd.shape;
                std::cout << log_ts() << "[Hailo] Loaded " << suffix
                          << " shape=[";
                for (int i = 0; i < (int)shape_out.size(); ++i)
                    std::cout << (i ? "," : "") << shape_out[i];
                std::cout << "]\n";
                return true;
            } catch (const std::exception& e) {
                std::cerr << log_ts() << "[Hailo] " << e.what() << "\n";
                return false;
            }
        };

        std::vector<int> emb_shape, pos_shape;
        bool have_emb = try_load("token_embedding_weight_tiny.npy",
                                 impl_->emb_weight, emb_shape);
        bool have_pos = try_load("onnx_add_input_tiny.npy",
                                 impl_->pos_emb,    pos_shape);

        if (have_emb && emb_shape.size() >= 2) {
            impl_->d_model = emb_shape[1]; // [vocab_size × d_model]
            std::cout << log_ts() << "[Hailo] d_model=" << impl_->d_model << "\n";
        }
        if (have_emb && have_pos && impl_->d_model > 0 &&
            !impl_->decoder.in_names.empty()) {
            // Derive fixed decode sequence length from the smaller decoder input
            size_t sz0 = impl_->decoder.input_size(impl_->decoder.in_names[0]);
            size_t sz1 = impl_->decoder.in_names.size() > 1
                       ? impl_->decoder.input_size(impl_->decoder.in_names[1]) : 0;
            size_t tok_bytes = (sz1 > 0 && sz1 < sz0) ? sz1 : sz0;
            impl_->dec_seq_len =
                static_cast<int>(tok_bytes / sizeof(float) / impl_->d_model);
            std::cout << log_ts() << "[Hailo] Decoder sequence length: "
                      << impl_->dec_seq_len << "\n";
        }

        if (!have_emb || !have_pos) {
            std::cerr << log_ts()
                << "[Hailo] WARNING: matmul-split embedding weights not found.\n"
                << "  Expected files in " << wdir << ":\n"
                << "    token_embedding_weight_tiny.npy\n"
                << "    onnx_add_input_tiny.npy\n"
                << "  Without them the decoder receives raw float token IDs instead\n"
                << "  of proper embeddings — output will be garbage.\n"
                << "  Extract with scripts/extract_whisper_weights.py or adjust\n"
                << "  the filenames to match your model size (base/small/medium).\n";
        }
    }

    // Log detected stream names and sizes
    std::cout << log_ts() << "[Hailo] Encoder inputs:\n";
    for (const auto& s : impl_->encoder.infer_model->inputs())
        std::cout << "  " << s.name() << "  " << s.get_frame_size() << " bytes\n";
    std::cout << log_ts() << "[Hailo] Encoder outputs:\n";
    for (const auto& s : impl_->encoder.infer_model->outputs())
        std::cout << "  " << s.name() << "  " << s.get_frame_size() << " bytes\n";
    std::cout << log_ts() << "[Hailo] Decoder inputs:\n";
    for (const auto& s : impl_->decoder.infer_model->inputs())
        std::cout << "  " << s.name() << "  " << s.get_frame_size() << " bytes\n";
    std::cout << log_ts() << "[Hailo] Decoder outputs:\n";
    for (const auto& s : impl_->decoder.infer_model->outputs())
        std::cout << "  " << s.name() << "  " << s.get_frame_size() << " bytes\n";

    // Summarise which decoder path will be taken at inference time so we can
    // verify the configuration without waiting for the first utterance.
    // Detect output format from the first decoder output buffer size.
    {
        int dec_chunks = static_cast<int>(impl_->decoder.infer_model->outputs().size());
        int pos_per_chunk = (dec_chunks > 0 && impl_->dec_seq_len > 0)
                          ? std::max(1, impl_->dec_seq_len / dec_chunks) : 1;
        size_t out0_bytes = 0;
        for (const auto& s : impl_->decoder.infer_model->outputs()) {
            out0_bytes = s.get_frame_size();
            break; // only need the first
        }
        size_t out0_floats       = out0_bytes / sizeof(float);
        size_t expect_logits     = (size_t)pos_per_chunk * VOCAB_SIZE;
        size_t expect_hidden     = (size_t)pos_per_chunk * std::max(impl_->d_model, 1);
        // Vocab-split: first (num_chunks-1) chunks may be pos_per_chunk floats
        // short because VOCAB_SIZE / num_chunks may not be an integer.
        bool output_is_logits    = (out0_floats + (size_t)pos_per_chunk >= expect_logits &&
                                    out0_floats <= expect_logits + 64);
        bool output_is_hidden    = (!output_is_logits && impl_->d_model > 0 &&
                                    out0_floats >= expect_hidden &&
                                    out0_floats <= expect_hidden + 64);

        std::string in_side  = (impl_->d_model > 0) ? "CPU-embed input" : "raw-id input";
        std::string out_side = output_is_logits ? "HEF-logit output (projection in NPU)"
                             : output_is_hidden ? "CPU-project output (projection on CPU)"
                             : "unknown output";

        std::cout << log_ts() << "[Hailo] Decoder mode: " << in_side
                  << " + " << out_side << "\n";
        if (impl_->d_model > 0)
            std::cout << log_ts() << "[Hailo]   d_model=" << impl_->d_model
                      << "  dec_seq_len=" << impl_->dec_seq_len
                      << "  out0=" << out0_floats << " floats"
                      << "  pos/chunk=" << pos_per_chunk
                      << "  expect_logits=" << expect_logits << "\n";
    }

    std::cout << log_ts() << "[Hailo] Ready.\n";
}

HailoTranscriber::~HailoTranscriber() = default;


std::string HailoTranscriber::transcribe(const std::vector<float>& pcm,
                                          bool               /*single_segment*/,
                                          int                /*audio_ctx*/,
                                          const std::string& /*initial_prompt*/) {
    if (pcm.empty()) return {};

    try {
        auto t0 = std::chrono::steady_clock::now();

        // 1. Log-mel spectrogram (CPU)
        auto mel = impl_->log_mel(pcm);

        // Debug: dump mel to a raw float32 file when VELAN_DUMP_MEL is set.
        // Compare against Python reference:
        //   import whisper, numpy as np
        //   audio = whisper.load_audio("test.wav")
        //   mel_ref = whisper.log_mel_spectrogram(audio)  # [80, 3000]
        //   mel_ref.numpy().tofile("mel_ref.bin")
        // Then: np.abs(np.fromfile("mel.bin",dtype=np.float32).reshape(80,-1) - mel_ref).max()
        const char* dump_path = std::getenv("VELAN_DUMP_MEL");
        if (dump_path && *dump_path) {
            std::ofstream df(dump_path, std::ios::binary);
            if (df) {
                // Write header: n_mels (int32), n_frames (int32), then float32 data
                int32_t hdr[2] = { N_MELS, (int32_t)(mel.size() / N_MELS) };
                df.write(reinterpret_cast<char*>(hdr), sizeof(hdr));
                df.write(reinterpret_cast<const char*>(mel.data()),
                         mel.size() * sizeof(float));
                std::cout << log_ts() << "[Hailo] Mel dumped: " << mel.size() / N_MELS
                          << " frames × " << N_MELS << " mels → " << dump_path << "\n";
                std::cout << log_ts() << "[Hailo] Compare with Python:\n"
                          << "  import whisper, numpy as np\n"
                          << "  m=np.frombuffer(open('" << dump_path << "','rb').read()[8:],dtype='f4').reshape(80,-1)\n"
                          << "  ref=whisper.log_mel_spectrogram('test.wav').numpy(); "
                          << "print(np.abs(m[:,:ref.shape[1]] - ref).max())\n";
            }
        }

        auto t1 = std::chrono::steady_clock::now();
        long mel_ms = std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count();

        // 2. Encoder (NPU)
        auto enc_out = impl_->run_encoder(mel);

        auto t2 = std::chrono::steady_clock::now();
        long enc_ms = std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

        // 3. Greedy decode (NPU, autoregressive)
        auto token_ids = impl_->greedy_decode(enc_out);

        auto t3 = std::chrono::steady_clock::now();
        long dec_ms = std::chrono::duration_cast<std::chrono::milliseconds>(t3 - t2).count();

        std::cout << log_ts() << "[Hailo] mel=" << mel_ms << "ms  enc=" << enc_ms
                  << "ms  dec=" << dec_ms << "ms  tokens=" << token_ids.size() << "\n";

        // 4. Detokenise
        return impl_->detokenise(token_ids);

    } catch (const std::exception& e) {
        std::cerr << log_ts() << "[Hailo] transcribe error: " << e.what() << "\n";
        return {};
    }
}
